name: 打包测试

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: 测试JDK打包

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: '8'
                    architecture: 'adopt'
            -   name: 构建
                run: mvn -B package --file pom.xml
